// Column mapping from old granular columns to new categorical columns
export const COLUMN_MAPPING = {
  // Direct mappings - columns that already exist in the new format
  'Advanced_Pain_Treatment': 'Advanced_Pain_Treatment',
  'Causation_Compliance': 'Causation_Compliance',
  'Clinical_Findings': 'Clinical_Findings',
  'Cognitive_Symptoms': 'Cognitive_Symptoms',
  'Complete_Disability_Duration': 'Complete_Disability_Duration',
  'Concussion_Diagnosis': 'Concussion_Diagnosis',
  'Consciousness_Impact': 'Consciousness_Impact',
  'Consistent_Mechanism': 'Consistent_Mechanism',
  'Dental_Procedure': 'Dental_Procedure',
  'Dental_Treatment': 'Dental_Treatment',
  'Dental_Visibility': 'Dental_Visibility',
  'Emergency_Treatment': 'Emergency_Treatment',
  'Fixation_Method': 'Fixation_Method',
  'Head_Trauma': 'Head_Trauma',
  'Immobilization_Used': 'Immobilization_Used',
  'Injury_Count': 'Injury_Count',
  'Injury_Extent': 'Injury_Extent',
  'Injury_Laterality': 'Injury_Laterality',
  'Injury_Location': 'Injury_Location',
  'Injury_Type': 'Injury_Type',
  'Mobility_Assistance': 'Mobility_Assistance',
  'Movement_Restriction': 'Movement_Restriction',
  'Nerve_Involvement': 'Nerve_Involvement',
  'Pain_Management': 'Pain_Management',
  'Partial_Disability_Duration': 'Partial_Disability_Duration',
  'Physical_Symptoms': 'Physical_Symptoms',
  'Physical_Therapy': 'Physical_Therapy',
  'Prior_Treatment': 'Prior_Treatment',
  'Recovery_Duration': 'Recovery_Duration',
  'Repair_Type': 'Repair_Type',
  'Respiratory_Issues': 'Respiratory_Issues',
  'Soft_Tissue_Damage': 'Soft_Tissue_Damage',
  'Special_Treatment': 'Special_Treatment',
  'Surgical_Intervention': 'Surgical_Intervention',
  'Symptom_Timeline': 'Symptom_Timeline',
  'Treatment_Compliance': 'Treatment_Compliance',
  'Treatment_Course': 'Treatment_Course',
  'Treatment_Delays': 'Treatment_Delays',
  'Treatment_Level': 'Treatment_Level',
  'Treatment_Period_Considered': 'Treatment_Period_Considered',
  'Vehicle_Impact': 'Vehicle_Impact',

  // Derived mappings - old columns that can be mapped to new categories
  'IMPACT': 'Vehicle_Impact', // Map numeric IMPACT to Vehicle_Impact categories
  'SETTLEMENT_DAYS': 'Recovery_Duration', // Can help determine recovery duration
  'causation_compliance': 'Causation_Compliance', // Numeric to categorical
  'causation_tx_delay': 'Treatment_Delays', // Delays factor
  'causation_tx_gaps': 'Treatment_Delays', // Gaps factor
  'severity_allowed_tx_period': 'Treatment_Period_Considered',
  'severity_initial_tx': 'Treatment_Course',
  'severity_injections': 'Pain_Management',
  'severity_objective_findings': 'Clinical_Findings',
  'severity_pain_mgmt': 'Pain_Management',
  'severity_type_tx': 'Treatment_Course',
};

// Valid values for each categorical column
export const CATEGORICAL_VALUES: Record<string, string[]> = {
  'Advanced_Pain_Treatment': ['No', 'Yes'],
  'Causation_Compliance': ['Compliant', 'Non-Compliant'],
  'Clinical_Findings': ['No', 'Yes', 'Mild', 'Moderate'],
  'Cognitive_Symptoms': ['Yes - Alleged', 'Yes - Diagnosed'],
  'Complete_Disability_Duration': ['Less than 1 week', 'Less than 2 Weeks', '1 -3 weeks', '2-4 Weeks', 'More than 8 Weeks', '2-6 Weeks', 'More than 6 Weeks', '5-8 Weeks', 'Less than 1 Week', 'More than 4 weeks', '1 - 3 Weeks', 'More than 4 Weeks'],
  'Concussion_Diagnosis': ['Yes', 'No'],
  'Consciousness_Impact': ['Temp Unconsciousness-Subjective', 'Temp Unconsciousness-Objective', 'Altered'],
  'Consistent_Mechanism': ['Consistent', 'Questionable', 'Highly Unlikely'],
  'Dental_Procedure': ['No', 'Yes'],
  'Dental_Treatment': ['Repair', 'Replace'],
  'Dental_Visibility': ['Yes', 'No'],
  'Emergency_Treatment': ['Yes - Treated & Released', 'Yes - Treated & Admitted', 'Yes - treated & released', 'Yes - treated & admitted'],
  'Fixation_Method': ['Open', 'ORIF w/o Hdw Removal', 'Open/Internal', 'Brace', 'Sling/Brace', 'Immobilization', 'Cast w/o Reduction', 'ORIF w/ Hdw Removal', 'Closed/External', 'Cast w/ Reduction', 'Hardware w/o Removal', 'Closed w/o Anesthesia', 'Closed w/ Anesthesia', 'External/Immobilization', 'Hardware w/ Removal', 'Closed', 'External', 'Wiring', 'Replacement', 'Vertebroplasty'],
  'Head_Trauma': ['No', 'Yes'],
  'Immobilization_Used': ['No', 'Yes', 'Brace/Sling', 'Cast', 'Brace/Boot'],
  'Injury_Count': ['Multi Level', 'Single Level', 'Single', 'Multiple', 'Two levels', 'Three or more levels', 'One', 'One level', 'Two or more', '2-3', 'More than 3'],
  'Injury_Extent': ['Mild', 'Moderate', 'Severe', 'No', 'Minor', 'Major'],
  'Injury_Laterality': ['Yes', 'No', 'Unilateral', 'Bilateral'],
  'Injury_Location': ['Cervical/Thoracic/Lumbar', 'Cervical/Lumbar', 'Cervical', 'Cervical/Thoracic', 'Lumbar', 'Thoracic/Lumbar', 'Thoracic'],
  'Injury_Type': ['Contusion Only', 'Herniation', 'Non-Displaced', 'Abrasion Only', 'Bruise/Hematoma w/Abrasion', 'Herniation/Protrusion/Extrusion', 'Bruise/Hematoma Only', 'Displaced', 'Bruise w/Abrasion', 'Annular Tear', 'Bruise Only', 'Compression/Wedge', 'Puncture w/Laceration', 'Transverse/Spinous Process'],
  'Mobility_Assistance': ['Crutches/Cane/Walker', 'Scooter/Wheelchair', 'Crutches/Cane/Walker/Scooter', 'Wheelchair'],
  'Movement_Restriction': ['Partial Restriction', 'No Restriction', 'Full Restriction', 'Partial ROM Restriction', 'Full ROM Restriction', 'No ROM Restriction'],
  'Nerve_Involvement': ['Yes', 'No'],
  'Pain_Management': ['RX', 'OTC', 'Rx', 'Single Injection', 'Multiple Injections', 'Single Epidural', 'Trigger Point(s)', 'Single Epidural/Nerve Block', 'Single Facet/Nerve Block', 'Multiple Epidural', 'Multiple Facet/Nerve Block', 'Multiple Epidural/Nerve Block', 'Single Trigger Point Injection', 'Radio Frequency Ablation'],
  'Partial_Disability_Duration': ['Less than 1 Week', '1 - 3 weeks', 'More than 4 weeks', 'Less than 2 Weeks', '2-4 Weeks', 'More than 8 Weeks', '2-6 Weeks', '1 - 3 Weeks', '5-8 Weeks', 'More than 6 Weeks'],
  'Physical_Symptoms': ['No', 'Yes', 'Yes - Alleged', 'Yes - Treated', 'Moderate', 'Severe', 'Mild'],
  'Physical_Therapy': ['Yes - Outpatient', 'Yes', 'No', 'Yes - Inpatient'],
  'Prior_Treatment': ['No', 'No/Non-Factor', 'Yes - Tx More than 1 Yr', 'No/Resolved', 'Yes - No Tx', 'Yes - Tx w/ 1 Yr', 'Yes - Actively Tx'],
  'Recovery_Duration': ['Less than 2 weeks', '2 - 4 weeks', '5 - 12 weeks', '2-4 weeks', 'More than 4 weeks', 'More than 12 weeks', 'More than 2 months', '1 - 2 months', 'Less than 3 Months', 'Less than 1 month', '2-6 Months', 'More than 3 Months', 'More than 6 Months'],
  'Repair_Type': ['Implant', 'Bridge', 'Crown', 'Filling/Bonding'],
  'Respiratory_Issues': ['No', 'Yes'],
  'Soft_Tissue_Damage': ['Partial Tear w/o Cart Damage', 'Partial Tear w/ Cart Damage', 'Full Tear w/o Cart Damage', 'Full Tear w/ Cart Damage', 'Cartilage only', 'Cartilage Only'],
  'Special_Treatment': ['No', 'Series', 'Single', 'Yes', 'Partial'],
  'Surgical_Intervention': ['No', 'Yes - Arthroscopic', 'Recommended Not Performed', 'Yes', 'Fusion', 'Yes - Open', 'Discectomy', 'Discectomy & Decompression Procedure', 'Micro discectomy', 'Decompression Procedure', 'Disc Replacement'],
  'Symptom_Timeline': ['Immediate/ER', 'First 48 Hours', '3 - 7 Days', 'More Than 7 Days', 'Immediate/Within 24 Hours', '2 - 4 days', '5 to 10 days', 'More than 10 Days', 'First 48 hours', 'More than 7 days', '3 to 7 days', '0 - 6 weeks', 'More than 12 months'],
  'Treatment_Compliance': [],
  'Treatment_Course': ['Active', 'Passive', 'Eval Only', 'None/Ice/Rest', 'Packing/Tape', 'Surgery - Single', 'Closed Reduction', 'Surgery - Multiple'],
  'Treatment_Delays': ['None/Explained', 'Delay Only', 'Gaps Only', 'Delay and Gaps'],
  'Treatment_Level': ['Non-Invasive', 'Yes', 'No', 'Clean & Dress', 'Stitches/Staples', 'Invasive', 'Stitches/Staples/Glue', 'Surgical Repair', 'Debridement/Drain', 'Immediate Surgical Repair'],
  'Treatment_Period_Considered': ['Less than 6 weeks', '7 - 12 weeks', '3 - 6 months', 'More than 6 months', 'Less than 6 months', '6 - 12 months', '0 - 6 weeks', '3-6 months', '6-12 months', 'Less than 3 months', '12 - 18 months', 'More than 12 months', 'More than 18 months', 'More than 12 weeks', '2 - 4 months', '4 - 6 months'],
  'Vehicle_Impact': ['Moderate', 'Heavy', 'Minimal'],
};

// Distribution weights for generating sample data (based on provided frequencies)
export const VALUE_WEIGHTS: Record<string, Record<string, number>> = {
  'Advanced_Pain_Treatment': {'No': 26930, 'Yes': 1011},
  'Causation_Compliance': {'Compliant': 1338076, 'Non-Compliant': 41882},
  'Clinical_Findings': {'No': 497354, 'Yes': 461477, 'Mild': 414, 'Moderate': 258},
  'Cognitive_Symptoms': {'Yes - Alleged': 26079, 'Yes - Diagnosed': 13837},
  'Vehicle_Impact': {'Moderate': 509269, 'Heavy': 343651, 'Minimal': 276613},
  'Emergency_Treatment': {'Yes - Treated & Released': 78571, 'Yes - Treated & Admitted': 5027},
  'Head_Trauma': {'No': 80342, 'Yes': 38824},
  'Injury_Extent': {'Mild': 104894, 'Moderate': 80346, 'Severe': 21062},
  'Movement_Restriction': {'Partial Restriction': 535617, 'No Restriction': 330541, 'Full Restriction': 15682},
  'Nerve_Involvement': {'Yes': 111854, 'No': 56658},
  'Pain_Management': {'RX': 439812, 'OTC': 210252, 'Rx': 176987, 'Single Injection': 36986},
  'Physical_Therapy': {'Yes - Outpatient': 16807, 'Yes': 12456, 'No': 11027, 'Yes - Inpatient': 5364},
  'Prior_Treatment': {'No': 720909, 'No/Non-Factor': 164453, 'Yes - Tx More than 1 Yr': 73427},
  'Treatment_Course': {'Active': 503949, 'Passive': 380651, 'Eval Only': 109996},
  'Treatment_Delays': {'None/Explained': 1094677, 'Delay Only': 163681, 'Gaps Only': 93899, 'Delay and Gaps': 68099},
};
